### ISSUE TITLE
Allow adding of "edit" messages in the front matter

### ISSUE THREAD

**Issue by lee-dohm** [lee-dohm/lee-dohm.github.io#22]
I imagine something looking like this:

``` yaml
layout: post
title: Some Long Title Nobody Cares About
tags: Tag
date: 2013-09-09 09:09:09.999 -07:00
edit:
  - First edit explanation
  - Second edit explanation
  - etc.
```

This will make it so that edit messages are only displayed on the article page, not the front page (where they would just be visual clutter).
